version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/thesis_grey
      - JWT_SECRET=your_jwt_secret_here
      - SERPER_API_KEY=your_serper_api_key_here

  db:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thesis_grey
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
